version: "3"

services:

  mongo:
    image: 'bitnami/mongodb:4.4'
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-db:/bitnami/mongodb'
  redis:
    image: 'bitnami/redis:6.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/bitnami/redis/data'

volumes:
  mongo-db:
    driver: local
  redis-data:
    driver: local

